nipy/nibabel

.gitmodules
nibabel/freesurfer/io.py
nibabel/freesurfer/tests/test_io.py

taking over #305
added hashing to support different versions of fsaverage files.

MRG : Freesurfer tests fix

---

doc/Makefile
doc/source/_templates/indexsidebar.html
doc/source/_templates/layout.html
doc/source/gitwash/known_projects.inc
doc/source/gitwash/this_project.inc
doc/source/index.rst
doc/source/links_names.txt

Move mailing list to neuroimaging@python.org

DOC: move mailing list

---

nisext/tests/test_testers.py

TST: Call current python executable in test_back_tick

---

nibabel/nifti1.py
nibabel/tests/test_nifti1.py

BF: Misplaced parenthesis

---

.mailmap
Changelog
doc/source/devel/make_release.rst
doc/source/index.rst
doc/source/links_names.txt
nibabel/info.py

Brings `master` docs into line with those generated in the process of releasing 2.0.2.

DOC: Update docs from 2.0.2 release

---

doc/source/installation.rst

There you go, was reading through stuff, found this.

DOC : Fixed typos in installation.rst

---

.travis.yml

Here I'm testing a new homu bot instance running on the nipy server.
See: https://github.com/barosl/homu and http://homu.io for more detail.
I'm going to try running a few homu commands to see whether they work.

WIP: testing the new homu bot

---

.travis.yml
dev-requirements.txt
doc-requirements.txt
doc/README.rst

pip requirements files for building docs and running tests.

MRG: add doc and dev requirements files

---

.travis.yml
nibabel/dft.py

This addresses #443 on my machine, but is clearly not the complete solution to this issue.

BF: Use newer call to frombytes, replacing fromstring.

---

nibabel/tests/test_scripts.py

BF: allow for int type string in ls on BE begin with <i

---

nibabel/nifti1.py

Update links for reference FreeSurfer matlab files.

DOC: Fieldtrip moved from Google Code to GitHub

---

nibabel/benchmarks/bench_streamlines.py
nibabel/casting.py
nibabel/imageclasses.py
nibabel/orientations.py
nibabel/spm2analyze.py

Fixes #499
The tests are passing on my machine, so it doesn't seem to break anything (that is currently tested). Let's see what happen with the Numpy pre-release.

BF: boolean indexing now requires matching dimension

---

doc/source/conf.py

Inspired by https://github.com/nipy/nibabel/pull/488 with thanks.

DOC: better warning when nibabel not on path

---

doc/source/coordinate_systems.rst

There will be inferior-superior axis 
not  inferior-posterior in human brain anatomy

fix: inferior-posterior to inferior-superior

---

doc/source/dicom/dicom_orientation.rst

Thanks to Joan Massich for pointing out the broken link and Chris M for
finding the corresponding link.

DOC: fix dicom link

---

doc/source/nifti_images.rst

Small typo correction in the Working with NIfTI images doc.

set sform with set_sform not get_sform

---

.travis.yml

See line 34:
https://github.com/nipy/nibabel/blob/34df0a6027fcde593c156ee0f50136bcf57d81f8/.travis.yml#L34-L36

CI: Remove duplicate Travis entry [skip ci]

---

.coveragerc
nibabel/analyze.py
nibabel/deprecated.py
nibabel/tests/test_analyze.py
nibabel/tests/test_arrayproxy.py
nibabel/tests/test_image_api.py
nibabel/tests/test_orientations.py
nibabel/tests/test_pkg_info.py
nibabel/tests/test_processing.py
nibabel/tests/test_quaternions.py
nibabel/tmpdirs.py

Just looking through the coverage report for easy fixes. Starting the PR to get a coverage report, to make sure I'm not breaking anything and increasing coverage where I think I am.
I plan to add to this intermittently, but feel free to comment or merge if it looks useful. (If it gets merged, I'll just start another PR next time I do any work of this sort.)

[WIP] TEST/RF: Increase coverage where easy

---

.travis.yml
nibabel/info.py

MAINT: Add six dependency

---

.zenodo.json

I added my ORCID and affiliation to the 2.5.1 release.

Add @hbraunDSP affiliation and ORCID

---

nibabel/externals/netcdf.py

Port of #821 with Python 3-only changes.

FIX: Re-import externals/netcdf.py from scipy (nibabel 3 port)

---

.travis.yml
nibabel/optpkg.py
nibabel/streamlines/tests/test_array_sequence.py
nibabel/streamlines/tests/test_tractogram.py
nibabel/tests/test_analyze.py
nibabel/tests/test_optpkg.py

@djarecka @robbisg If you're both good with these updates, feel free to merge.

TEST: Cleanups

---

nisext/tests/test_sexts.py
nisext/tests/test_testers.py

When I simply launch pytest, it fails.

TEST: Purge nose from nisext tests

---

Changelog
nibabel/benchmarks/bench_arrayproxy_slicing.py
setup.cfg

Preparation for bug-fix release 3.2.1, for immediate release.
No pending PRs address bugs, and I don't feel a need to finish the GitHub migration prior to release.
--------
Closes #970.
Closes #973.

REL: 3.2.1

---

nibabel/gifti/gifti.py
nibabel/volumeutils.py

FIX: Added a few missing commas to deprecations

---

.github/workflows/misc.yml
.github/workflows/pre-release.yml
.github/workflows/stable.yml

Lost this when we moved from Travis.

CI: Run stable tests weekly, pre-release tests nightly

---

.github/workflows/pre-release.yml
nibabel/wrapstruct.py

Python discourse is recommending 3.10 wheels get uploaded during the RC phase.
https://discuss.python.org/t/encouraging-3-10-wheels-on-pypi/10207
Let's see if it can be this easy...

CI: Test on Python 3.10

---

.gitmodules

MNT: Update submodule URLs to use https

---

pyproject.toml

STY: Add blue to style dependencies

---

.zenodo.json

Update affiliation of jhlegarreta.

DOC: Update affiliation of jhlegarreta

---

.readthedocs.yaml

Rendered doc: https://nibabel-draft--1398.org.readthedocs.build/en/1398

doc: Build on ReadTheDocs for PR previews

---

.readthedocs.yaml

chore(rtd): Build API docs
